"""Compare program outputs with the reference outputs of the debug sets.

Usage:
    python scripts/compare_debug.py --assignment pa1

Reads ``output/<set>-output1.txt`` (written by ``python -m cisnav.pa1``) and the
reference ``data/pa1/<set>-output1.txt``, and writes a Markdown report to
``results/pa1_validation.md``.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from cisnav import io
from cisnav.registration import register, rms_error

ROOT = Path(__file__).resolve().parents[1]

# Handout page 13: which error sources are switched on (distortion, noise, jiggle).
ERROR_SOURCES = {
    "pa1": {
        "a": (0, 0, 0), "b": (0, 1, 0), "c": (1, 0, 0), "d": (0, 0, 1),
        "e": (1, 0, 1), "f": (1, 1, 1), "g": (1, 1, 1),
    },
    "pa2": {
        "a": (0, 0, 0), "b": (0, 1, 0), "c": (1, 0, 0), "d": (0, 0, 1),
        "e": (1, 1, 1), "f": (1, 1, 1),
    },
}


@dataclass
class Stats:
    max: float
    rms: float

    @classmethod
    def of(cls, a: np.ndarray, b: np.ndarray) -> Stats:
        d = np.linalg.norm(np.asarray(a) - np.asarray(b), axis=-1).ravel()
        return cls(float(d.max()), float(np.sqrt(np.mean(d**2))))


def _yn(flag: int) -> str:
    return "yes" if flag else "no"


def _sources(assignment: str, letter: str) -> str:
    dist, noise, jiggle = ERROR_SOURCES[assignment][letter]
    return f"{_yn(dist)} | {_yn(noise)} | {_yn(jiggle)}"


def reference_rigidity(cal: io.CalBody, C: np.ndarray) -> float:
    """Worst per-frame RMS residual of a rigid fit of ``c`` to the points ``C``.

    A true ``F_D^-1 F_A c`` is a rigid image of ``c``, so this is zero up to
    rounding. A large value means ``C`` contains EM-side error.
    """
    return max(rms_error(register(cal.c, Ck), cal.c, Ck) for Ck in C)


def projection_coefficient(diff: np.ndarray, em_error: np.ndarray) -> float:
    """Least-squares ``alpha`` in ``diff ~= alpha * em_error``.

    ``diff`` is reference minus ours and ``em_error`` is measured C minus ours.
    ``alpha = 1`` means the reference contains the full EM error; ``alpha = 0``
    means the difference is unrelated to it.
    """
    x, y = em_error.ravel(), diff.ravel()
    return float(x @ y / (x @ x)) if x @ x > 0 else float("nan")


def neighbour_correlation(cal: io.CalBody, diff: np.ndarray) -> float:
    """Correlation of ``diff`` between neighbouring markers of the calibration grid.

    Independent noise gives about 0; a smooth error field gives a clearly
    positive value.
    """
    dist = np.linalg.norm(cal.c[:, None] - cal.c[None], axis=-1)
    step = np.min(dist[dist > 0])
    i, j = np.nonzero(np.isclose(dist, step))
    return float(np.corrcoef(diff[:, i].ravel(), diff[:, j].ravel())[0, 1])


def pa1_report(data_dir: Path, out_dir: Path) -> str:
    rows, diag = [], []
    for letter in ERROR_SOURCES["pa1"]:
        prefix = f"pa1-debug-{letter}"
        ref = io.read_output1(io.data_path(data_dir, prefix, "output1"))
        ours = io.read_output1(out_dir / f"{prefix}-output1.txt")
        cal = io.read_calbody(io.data_path(data_dir, prefix, "calbody"))
        readings = io.read_calreadings(io.data_path(data_dir, prefix, "calreadings"))

        c = Stats.of(ours.C_expected, ref.C_expected)
        em = np.linalg.norm(ours.em_post - ref.em_post)
        opt = np.linalg.norm(ours.opt_post - ref.opt_post)
        rows.append(
            f"| {letter} | {_sources('pa1', letter)} | {c.max:.3f} | {c.rms:.3f} "
            f"| {em:.3f} | {opt:.3f} |"
        )
        meas = Stats.of(readings.C, ours.C_expected)
        diff = ref.C_expected - ours.C_expected
        if c.rms > 0.05:
            alpha = f"{projection_coefficient(diff, readings.C - ours.C_expected):.3f}"
            corr = f"{neighbour_correlation(cal, diff):.2f}"
        else:
            alpha = corr = "n/a"
        diag.append(
            f"| {letter} | {reference_rigidity(cal, ours.C_expected):.3f} "
            f"| {reference_rigidity(cal, ref.C_expected):.3f} "
            f"| {meas.rms:.3f} | {alpha} | {corr} |"
        )

    return "\n".join(
        [
            "# PA1 validation against the debug sets",
            "",
            "Generated by `python scripts/compare_debug.py --assignment pa1` from the",
            "files in `output/` and the reference `data/pa1/*-output1.txt`. All values",
            "are in millimetres. Both files are rounded to 0.01 mm, so a difference of",
            "up to about 0.01 mm per coordinate (0.017 mm as a 3D distance) is rounding.",
            "",
            "## Errors against the reference output",
            "",
            "C_expected errors are 3D distances over all 27 markers and 8 frames. The",
            "post errors are 3D distances between our post and the reference post.",
            "",
            "| Set | EM distortion | EM noise | OT jiggle | C_expected max | C_expected RMS "
            "| EM post | Optical post |",
            "|---|---|---|---|---|---|---|---|",
            *rows,
            "",
            "## Diagnostics",
            "",
            "- **Rigidity** is the worst per-frame RMS residual after rigidly",
            "  registering the calibration body markers `c` to a set of 27 points. The",
            "  true expected positions `F_D^-1 F_A c` are a rigid image of `c` by",
            "  definition, so their rigidity residual is zero up to rounding.",
            "- **EM error** is the RMS distance between the measured EM readings `C`",
            "  and our C_expected: the total distortion and noise in the readings.",
            "- **alpha** is the least-squares coefficient in",
            "  `(reference - ours) ~= alpha (measured C - ours)`. A value of 1 means the",
            "  reference contains the full EM error; 0 means the difference has",
            "  nothing to do with it.",
            "- **Neighbour correlation** is the correlation of `reference - ours`",
            "  between adjacent markers of the calibration grid. Independent noise",
            "  gives about 0; a smooth error field gives a clearly positive value.",
            "",
            "| Set | Rigidity of our C_expected | Rigidity of reference C_expected "
            "| EM error RMS | alpha | Neighbour correlation |",
            "|---|---|---|---|---|---|",
            *diag,
            "",
            "## Interpretation",
            "",
            "**Pivot calibrations match every set.** The EM and optical post positions",
            "agree with the reference to rounding in all seven debug sets, including",
            "the ones with distortion, noise and jiggle. For the EM pivot this means the",
            "reference was computed the same way, from the distorted readings, so the",
            "distortion bias is present in both. The optical pivot is unaffected by EM",
            "error, and its agreement in sets d to g shows that mapping each frame",
            "through its own `F_D` removes the tripod jiggle.",
            "",
            "**C_expected matches when the EM tracker is error free.** Sets a and d",
            "agree to rounding. Set d is slightly above a because the jiggle changes",
            "`F_D` in every frame, and the 0.01 mm rounding of the `D` readings is",
            "amplified by the lever arm from the EM base markers to the calibration",
            "object.",
            "",
            "**For sets with EM noise or distortion the reference C_expected is not a",
            "noise-free expected value.** C_expected depends only on the optical",
            "readings `D` and `A` and the body geometry, so EM noise and distortion",
            "cannot change it. Two observations show that the reference files contain",
            "EM-side error anyway:",
            "",
            "- In set b (EM noise only) the reference C_expected is identical, to the",
            "  last digit, to the measured EM readings `C` (alpha = 1). The difference",
            "  between our values and the reference is exactly the injected EM noise,",
            "  about 0.5 mm RMS as a 3D distance (0.28 mm per coordinate), and it is",
            "  uncorrelated between neighbouring markers, as noise should be.",
            "- In sets c, e, f and g the reference is no longer a rigid image of `c`",
            "  (rigidity residual 0.46 to 2.1 mm, against 0.005 mm for ours). It does",
            "  not contain the distortion seen in the measured readings (alpha is",
            "  close to 0, while that distortion is 3.5 to 7 mm RMS), but it does",
            "  contain a smaller error field of its own, which is spatially smooth",
            "  (neighbour correlation above 0.5). The sets where this field appears are",
            "  exactly the sets with EM distortion switched on.",
            "",
            "We could not identify how the reference generator produces this field.",
            "One hypothesis was tested and rejected: that the reference is the",
            "measured `C` after a polynomial distortion correction. Fitting our own",
            "Bernstein correction of degree 1 to 3 to these frames and applying it to",
            "`C` gives points that are no closer to the reference than our C_expected",
            "is (for example 0.48 mm against 0.40 mm RMS in set c at degree 3).",
            "",
            "Our C_expected is a rigid image of `c` in every set, within 0.01 mm, which",
            "is what the definition `F_D^-1 F_A c` requires. Changing the program to",
            "match the reference in these sets would mean adding EM error back in, so",
            "the program was left as it is. The errors are the expected outcome given",
            "which error sources each set has switched on, not a bug.",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--assignment", choices=["pa1"], default="pa1")
    parser.add_argument("--data-dir", type=Path, default=None)
    parser.add_argument("--out-dir", type=Path, default=ROOT / "output")
    parser.add_argument("--results-dir", type=Path, default=ROOT / "results")
    args = parser.parse_args(argv)

    data_dir = args.data_dir or ROOT / "data" / args.assignment
    text = pa1_report(data_dir, args.out_dir)
    args.results_dir.mkdir(parents=True, exist_ok=True)
    path = args.results_dir / f"{args.assignment}_validation.md"
    path.write_text(text)
    print(text)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
